version: "3.7"

services:
    http-proxy:
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - SQUID_VERSION=${SQUID_VERSION}
        container_name: ${CONTAINER}
        hostname: ${CONTAINER}
        image: ${REPOSITORY}:${TAG}
        restart: always
        tty: true
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${PATH_DOCKER_VOLUME}/${CONTAINER}/init.d:/opt/local/etc/init.d
            - ${PATH_DOCKER_VOLUME}/${CONTAINER}/squid.etc:/opt/local/etc/squid
            - ${PATH_DOCKER_VOLUME}/${CONTAINER}/squid.spool:/var/spool/squid
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://172.17.0.1:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        ports:
            - "${SQUID_PUBLIC}:3128"
        network_mode: "bridge"
