# == Overwrite sshd Recommended setting ==

## ログイン情報を取得する為にファシリティを変更(Facility)
LogLevel VERBOSE
## SSH プロトコルバージョン2 のみをサポート
Protocol 2
## サーバーホストの秘密鍵を選択(docker-compose.yml の volumes と関連あり)
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
## 公開鍵認証の有効化
PubkeyAuthentication yes
## パスワード認証の無効化
PasswordAuthentication no
## 空パスワードを許可しな
PermitEmptyPasswords no
## root ユーザのログインを許可しない
PermitRootLogin no
## チャレンジレスポンス認証の無効化(パスワード認証の無効化とセットで無効化とすること)
ChallengeResponseAuthentication no
## ポートフォワードを許可(ProxyCommand -W)
AllowTcpForwarding yes
## Interval * CountMax 秒反応できない SSH クライアントを切断
ClientAliveInterval 120
ClientAliveCountMax 3
