version: '3.7'

services:
    bird-A-0:
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile-bird
            args:
                - BIRD_BRANCH=${BIRD_BRANCH}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${HOME}/docker.volume/bird-A-0/bird/etc:/opt/bird/etc
            - ${HOME}/docker.volume/bird-A-0/local/etc:/opt/local/etc
        image: ${REPOSITORY}:${TAG}
        container_name: bird-A-0
        hostname: bird-A-0
        tty: true
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://{{syslog_srv}}:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        cap_add:
            - NET_ADMIN
        networks:
            redundant-link0:
                ipv4_address: 10.10.20.10
            redundant-link1:
                ipv4_address: 10.10.21.10
            external-link0:
                ipv4_address: 10.10.30.10
            gwbridge:
    bird-A-1:
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile-bird
            args:
                - BIRD_BRANCH=${BIRD_BRANCH}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${HOME}/docker.volume/bird-A-1/bird/etc:/opt/bird/etc
            - ${HOME}/docker.volume/bird-A-1/local/etc:/opt/local/etc
        image: ${REPOSITORY}:${TAG}
        container_name: bird-A-1
        hostname: bird-A-1
        tty: true
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://{{syslog_srv}}:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        cap_add:
            - NET_ADMIN
        networks:
            redundant-link0:
                ipv4_address: 10.10.20.11
            redundant-link1:
                ipv4_address: 10.10.21.11
            external-link1:
                ipv4_address: 10.10.31.11
            gwbridge:
    bird-B-0:
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile-bird
            args:
                - BIRD_BRANCH=${BIRD_BRANCH}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${HOME}/docker.volume/bird-B-0/bird/etc:/opt/bird/etc
            - ${HOME}/docker.volume/bird-B-0/local/etc:/opt/local/etc
        image: ${REPOSITORY}:${TAG}
        container_name: bird-B-0
        hostname: bird-B-0
        tty: true
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://{{syslog_srv}}:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        cap_add:
            - NET_ADMIN
        networks:
            redundant-link0:
                ipv4_address: 10.10.20.20
            internal-link:
                ipv4_address: 10.10.40.20
            gwbridge:
    bird-B-1:
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile-bird
            args:
                - BIRD_BRANCH=${BIRD_BRANCH}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${HOME}/docker.volume/bird-B-1/bird/etc:/opt/bird/etc
            - ${HOME}/docker.volume/bird-B-1/local/etc:/opt/local/etc
        image: ${REPOSITORY}:${TAG}
        container_name: bird-B-1
        hostname: bird-B-1
        tty: true
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://{{syslog_srv}}:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        cap_add:
            - NET_ADMIN
        networks:
            redundant-link1:
                ipv4_address: 10.10.21.21
            internal-link:
                ipv4_address: 10.10.40.21
            gwbridge:
    bird-gobgp:
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile-gobgp
            args:
                - GOBGP_BRANCH=${GOBGP_BRANCH}
                - GO_VERSION=${GO_VERSION}
                - GO_SHA256_CHECKSUM=${GO_SHA256_CHECKSUM}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${HOME}/docker.volume/bird-gobgp/go/etc:/root/go/etc
            - ${HOME}/docker.volume/bird-gobgp/local/etc:/opt/local/etc
        image: ${GOBGP_REPOSITORY}:${GOBGP_TAG}
        container_name: bird-gobgp
        hostname: bird-gobgp
        tty: true
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://{{syslog_srv}}:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        cap_add:
            - NET_ADMIN
        networks:
            redundant-link0:
                ipv4_address: 10.10.20.40
            redundant-link1:
                ipv4_address: 10.10.21.40
            gwbridge:
    ToR-0:
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile-bird
            args:
                - BIRD_BRANCH=${BIRD_BRANCH}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${HOME}/docker.volume/bird-ToR-0/bird/etc:/opt/bird/etc
            - ${HOME}/docker.volume/bird-ToR-0/local/etc:/opt/local/etc
        image: ${REPOSITORY}:${TAG}
        container_name: ToR-0
        hostname: ToR-0
        tty: true
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://{{syslog_srv}}:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        cap_add:
            - NET_ADMIN
        networks:
            external-link0:
                ipv4_address: 10.10.30.30
            gwbridge:
    ToR-1:
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile-bird
            args:
                - BIRD_BRANCH=${BIRD_BRANCH}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${HOME}/docker.volume/bird-ToR-1/bird/etc:/opt/bird/etc
            - ${HOME}/docker.volume/bird-ToR-1/local/etc:/opt/local/etc
        image: ${REPOSITORY}:${TAG}
        container_name: ToR-1
        hostname: ToR-1
        tty: true
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://{{syslog_srv}}:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        cap_add:
            - NET_ADMIN
        networks:
            external-link1:
                ipv4_address: 10.10.31.30
            gwbridge:

networks:
    redundant-link0:
        name: bfd-redundant0
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.10.20.0/24"
    redundant-link1:
        name: bfd-redundant1
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.10.21.0/24"
    external-link0:
        name: bfd-external0
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.10.30.0/24"
    external-link1:
        name: bfd-external1
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.10.31.0/24"
    internal-link:
        name: bfd-internal
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.10.40.0/24"
    gwbridge:
        external:
            name: docker_gwbridge

