---
- hosts: localhost
  connection: local
  tasks:
  roles:
    - sshkey-into-con
  gather_facts: no

- name: apt-get
  hosts: linux_nodes
  roles:
    - check-tags
    - apt-get
  gather_facts: no

