---
- hosts: localhost
  connection: local
  tasks:
  roles:
    - sshkey-into-con
  gather_facts: no

- name: base-config
  hosts: linux_nodes
  roles:
    - check-tags
    - base-config
  gather_facts: no

