version: '3.7'

#
# [docker-compose.yaml](https://qiita.com/m0559reen/items/d593c526af64c29293f5#docker-composeyaml)
#

services:
    ansible:
        env_file:
            - ./.env
        build:
            context: ./Dockerfiles
            dockerfile: Dockerfile
            args:
                - LOGIN_USER=${LOGIN_USER}
                - LOGIN_UID=${LOGIN_UID}
                - LOGIN_GID=${LOGIN_GID}
                - LOGIN_USER_PASSWORD=${LOGIN_USER_PASSWORD}
                - ADD_LOCALE=${ADD_LOCALE}
                - SET_LOCALE=${SET_LOCALE}
                - LC_ALL=${LC_ALL}
        image: ${REPOSITORY}:${TAG}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./:/var/opt/ansible:rw
        container_name: ansible-con
        hostname: ansible-srv
        tty: true
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://{{syslog_srv}}:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        #cap_add:
        #    - NET_ADMIN
        network_mode: "bridge"
        entrypoint:
            - ansible
    ansible-playbook:
        env_file:
            - ./.env
        image: ${REPOSITORY}:${TAG}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./:/var/opt/ansible:rw
        image: ${REPOSITORY}:${TAG}
        container_name: ansible-playbook-con
        hostname: ansible-srv
        tty: true
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://{{syslog_srv}}:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        #cap_add:
        #    - NET_ADMIN
        network_mode: "bridge"
        entrypoint:
            - ansible-playbook
    ansible-shell:
        env_file:
            - ./.env
        image: ${REPOSITORY}:${TAG}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./:/var/opt/ansible:rw
            - /var/tmp/ansible-shell/${HOSTNAME_ANSIBLE_SHELL_CON}:/var/tmp/ansible-shell:rw
        image: ${REPOSITORY}:${TAG}
        container_name: ${HOSTNAME_ANSIBLE_SHELL_CON}
        hostname: ${HOSTNAME_ANSIBLE_SHELL_CON}
        tty: true
        logging:
            driver: "syslog"
            options:
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        network_mode: "bridge"
        entrypoint:
            - bash

