version: '3'

services:
    portainer:
        container_name: my-portainer
        hostname: my-portainer
        image: portainer/portainer
        ports:
            - "19000:9000"
        network_mode: "bridge"
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - data:/data
        restart: always

volumes:
    data:

