version: '3.7'

services:
    ssh-bastion:
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - LOGIN_UID=${LOGIN_UID}
                - LOGIN_GID=${LOGIN_GID}
                - LOGIN_USER=${LOGIN_USER}
                - LOGIN_USER_PASSWORD=${LOGIN_USER_PASSWORD}
                - CONTAINER=${CONTAINER}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
            - ${HOME}/docker.volume/${CONTAINER}:/home/${LOGIN_USER}/volume
        container_name: ${CONTAINER}
        hostname: ${CONTAINER}
        image: ${REPOSITORY}:${TAG}
        restart: always
        tty: true
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://192.168.1.2:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        ports:
            - "${PUBLIC_SSH}:22"
        network_mode: "bridge"

