version: '3.7'

# == Docker network ==
# $ sudo docker network create --driver bridge \
# > --subnet 192.168.1.0/24 --gateway 192.168.1.2 \
# > --opt "com.docker.network.bridge.name"="br_mgmt0" br-mgmt0
services:
    ssh-bastion:
        env_file:
            - ./.env
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - LOGIN_UID=${LOGIN_UID}
                - LOGIN_GID=${LOGIN_GID}
                - LOGIN_USER=${LOGIN_USER}
                - LOGIN_USER_PASSWORD=${LOGIN_USER_PASSWORD}
                - CONTAINER=${CONTAINER}
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/ssh/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
            - ${HOME}/docker.volume/${CONTAINER}:/home/${LOGIN_USER}/volume
        container_name: ${CONTAINER}
        hostname: ${CONTAINER}
        image: ${REPOSITORY}:${TAG}
        restart: always
        tty: true
        logging:
            driver: "syslog"
            options:
                #syslog-address: udp://192.168.1.2:514
                syslog-facility: "daemon"
                tag: "{{.DaemonName}}/{{.ImageName}}/{{.Name}}"
        cap_add:
            - NET_ADMIN
        networks:
            br-mgmt0:
                ipv4_address: ${IPV4_ADDRESS}
networks:
    br-mgmt0:
        external: true
        driver: bridge
        driver_opts:
            com.docker.network.bridge.name: br_mgmt0
        ipam:
            driver: default
            config:
                - subnet: ${IPV4_SUBNET}

